## Rename Features ##
feature_name_dict = {
 'F_medCat__5HT3_receptor_antagonists': '5HT3 receptor antagonists',
 'F_anyNarcotic': 'any Narcotic',
 'F_anyNSAID': 'any NSAID',
 'F_anyBenzo': 'any Benzo',
 'F_medCat__SSNRI_antidepressants': 'SSNRI antidepressants',
 'F_medCat__SSRI_antidepressants': 'SSRI antidepressants',
 'F_medCat__factor_Xa_inhibitors': 'factor Xa inhibitors',
 'F_medCat__gamma-aminobutyric_acid_analogs': 'gamma-aminobutyric acid analogs',
 'F_medCat__miscellaneous_analgesics': 'miscellaneous analgesics',
 'F_medCat__miscellaneous_anticonvulsants': 'miscellaneous anticonvulsants',
 'F_medCat__miscellaneous_antidepressants': 'miscellaneous antidepressants',
 'F_medCat__miscellaneous_anxiolytics,_sedatives_and_hypnotics': 'miscellaneous anxiolytics, sedatives and hypnotics',
 'F_medCat__phenothiazine_antiemetics': 'phenothiazine antiemetics',
 'F_medCat__phenothiazine_antipsychotics': 'phenothiazine antipsychotics',
 'F_medCat__phenylpiperazine_antidepressants': 'medCat__phenylpiperazine antidepressants',
 'F_medCat__proton_pump_inhibitors': 'proton pump inhibitors',
 'F_medCat__skeletal_muscle_relaxants': 'skeletal muscle relaxants',
 'F_AGEINYEARS': 'age',
 'F_HASHYPERTENSION': 'hypertension',
 'F_MI': 'MI',
 'F_CHF': 'CHF',
 'F_PVD': 'PVD',
 'F_STROKE': 'Stroke',
 'F_PUD': 'PUD',
 'F_LIVERDISEASE': 'liver disease',
 'F_RHEUM': 'rheum',
 'F_DIABETES': 'diabetes',
 'F_COPD': 'COPD',
 'F_KIDNEYDISEASE': 'kidney disease',
 'F_CANCER': 'cancer',
 'F_DEMENTIA': 'dementia',
 'F_HEMIPLEGIA': 'hemiplegia',
 'F_AfricanAmerican': 'African American',
 'F_Asian': 'Asian',
 'F_Caucasian': 'Caucasian',
 'F_Hispanic': 'Hispanic',
 'F_Male': 'Male',
 'F_averageBMI': 'average BMI',
 'F_glucoseMedian': 'glucose median',
 'F_glucoseLast': 'glucose last',
 'F_SodiumMedian': 'sodium median',
 'F_SodiumLast': 'sodium last',
 'F_ALTMedian': 'ALT median',
 'F_ALTLast': 'ALT last',
 'F_plateletsMedian': 'platelets median',
 'F_plateletsLast': 'platelets last',
 'F_GFRMedian': 'GFR median',
 'F_GFRLast': 'GFR last',
 'F_CreatinineMedian': 'creatinine median',
 'F_CreatinineLast': 'creatinine last',
 'F_systolicMedian': 'systolic median',
 'F_systolicLast': 'systolic last',
 'F_diastolicMedian': 'diastolic median',
 'F_diastolicLast': 'diastolic last',
 'F_countPriorER': 'count prior ER',
 'F_countPriorAdmits': 'count prior admits'}